# Required to run your project under the correct environment.
language: php
# Versions of PHP you want your project run with.
php:
 - 7.2
# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction
 - mkdir -p build/logs
# Commands you want to run that will verify your build.
script:
 - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
## Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
 fast_finish: true
# Customize when the notification emails are sent.
notifications:
   on_success: never
   on_failure: always
